#!/usr/bin/env bash

export EDITOR="nvim"
export HISTCONTROL=ignoredups
export HISTFILESIZE=10000
export HISTIGNORE="ls:ls *:cd:cd -:pwd:exit:* --help:* -h"
export ZSH_TMUX_AUTOSTART=true
export ZSH_TMUX_AUTOSTART_ONCE=false
