#!/usr/bin/env bash

install_packages() {
  wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
  sudo sh -c 'echo "deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'

  sudo apt update
  sudo apt install -y git zsh tmux silversearcher-ag neovim gnome-tweaks autojump google-chrome-stable
  header "Installed packages..."
  success "git zsh tmux silversearcher-ag neovim gnome-tweaks autojump google-chrome-stable"
}
