#!/usr/bin/env bash

install_packages() {
  wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
  sudo sh -c 'echo "deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'

  sudo add-apt-repository universe
  sudo apt update
  sudo apt install -y curl wget git zsh tmux silversearcher-ag neovim gnome-tweaks autojump google-chrome-stable sysstat steam
  header "Installed packages..."
  success "curl wget git zsh tmux silversearcher-ag neovim gnome-tweaks autojump google-chrome-stable sysstat steam"
  sudo snap install slack --classic
  sudo snap install spotify
  header "Installed snaps..."
  success "slack spotify"
}
