#!/usr/bin/env bash

install_packages() {
  sudo add-apt-repository universe
  sudo add-apt-repository multiverse
  success "Added universe and multiverse repositories"

  sudo apt update
  sudo apt install -y software-properties-common git zsh tmux wget silversearcher-ag neovim gnome-tweaks gparted steam
  header "Installed packages..."
  success "software-properties-common git zsh tmux wget silversearcher-ag neovim gnome-tweaks gparted steam"
  sudo snap install slack --classic
  sudo snap install spotify
  success "slack spotify"

  wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
  sudo sh -c 'echo "deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'

  sudo apt update
  sudo apt install -y google-chrome-stable
  success "chrome"
}
